spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/qcws-live?useUnicode=true&amp;characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: admin
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    # 最多连接数量
    maxActive: 300
    # 没有使用时,回收的最长时间
    maxWait: 10000
    # 最多的空闲连接数
    maxIdle: 1000
    # 最少空闲连接数
    minIdle: 100
    # 初始连接数
    initialSize: 10
    # 是否自动回收超时连接
    removeAbandoned: true
    # 超时时间(以秒为单位)
    removeAbandonedTimeout: 30
    # 打开检查,用异步线程evict进行检查
    testWhileIdle: true
    # 指定空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔,与testWhileIdle一起使用
    timeBetweenEvictionRunsMillis: 300000
    # 获取连接前是否运行validationQuery,true=运行(默认),false=不运行
    testOnBorrow: true
    # 将连接归还连接池前是否运行validationQuery,true=运行,false=不运行(默认)
    testOnReturn: false
    # 检查连接,应用SQL语句执行之前运行一次
    validationQuery: select 1
    # 回收资源的数量
    numTestsPerEvictionRun: 20
    # 资源最小空闲时间
    minEvictableIdleTimeMillis: 1800000
    jackson:
      default-property-inclusion: non_null

config:
  jedis :
    pool :
      host : 192.168.1.236
      port : 6380
    maxTotal: 200
    maxIdle: 50
    minIdle: 10
    maxWaitMillis : 10000
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
    seconds : 1800
    timeBetweenEvictionRunsMillis: 30000
    numTestsPerEvictionRun: 10
    minEvictableIdleTimeMillis: 60000


qcws:
  #  网站域名
  url: http://qctest.oss-cn-shenzhen.aliyuncs.com
  # 前端默认图片
  defaultImg: data/1499342748893.png

aliyunOSS:
  # 会员头像图片路径
  headerFileDir: member/header/
  # 会员反馈描述图片路径
  feedbackImgFileDir: member/feedback/
  # 营业执照图片路径
  licenseFileDir: user/businesslicense/
  # 身份证正反面图片路径
  IDCardFileDir: user/idcard/
  # logo图片路径
  logoFileDir: user/logo/
  # 开户银行图片路径
  bankCardFileDir: user/bankcard/
  # 合同
  leaseContractFileDir: user/leaseContract/
  # 资质证明
  qualificationFileDir: user/qualification/
  # 开发/测试的空间
  bucketName: qctest
  endpoint: http://oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAIqM1yei0xXdQ7
  accessKeySecret: 0T01csJF2SvRsFybw9X1g8s6dGxDO9