spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qcws-live?useUnicode=true&characterEncoding=utf-8&ssl=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    # 最多连接数量
    maxActive: 100
    # 没有使用时,回收的最长时间
    maxWait : 10000
    # 最多空闲连接数
    maxIdle : 30
    # 最少空闲连接数
    minIdle : 5
    # 初始连接数
    initialSize: 5
    # 是否自动回收超时连接
    removeAbandoned : true
    # 超时时间(以秒数为单位)
    removeAbandonedTimeout : 60
    # 打开检查,用异步线程evict进行检查
    testWhileIdle : true
    # 获取连接前是否运行validationQuery,true=运行[默认],false=不运行
    testOnBorrow : true
    # 将连接归还连接池前是否运行validationQuery,true=运行,false=不运行[默认]
    testOnReturn : false
    # 检查连接,应用的SQL语句执行之前运行一次
    validationQuery : select 1
    # 回收资源的数量
    numTestsPerEvictionRun : 20
    # 资源最小空闲时间
    minEvictableIdleTimeMillis : 18000
    timeBetweenEvictionRunsMillis: 10000

config:
  jedis :
    pool :
      host : 127.0.0.1
      port : 6379
      pwd : 123456
    maxTotal: 200
    maxIdle: 50
    minIdle: 10
    maxWaitMillis : 10000
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
    seconds : 1800
    timeBetweenEvictionRunsMillis: 30000
    numTestsPerEvictionRun: 10
    minEvictableIdleTimeMillis: 60000

java:
  secretKey: appPayJson

qcws:
  #  网站域名
  url: http://qctest.oss-cn-shenzhen.aliyuncs.com
  # 前端默认图片
  defaultImg: data/1499342748893.png

aliyunOSS:
  # 会员头像图片路径
  headerFileDir: member/header/
  # 会员反馈描述图片路径
  feedbackImgFileDir: member/feedback/
  # 营业执照图片路径
  licenseFileDir: user/businesslicense/
  # 身份证正反面图片路径
  IDCardFileDir: user/idcard/
  # logo图片路径
  logoFileDir: user/logo/
  # 开户银行图片路径
  bankCardFileDir: user/bankcard/
  # 合同
  leaseContractFileDir: user/leaseContract/
  # 资质证明
  qualificationFileDir: user/qualification/
  # 开发/测试的空间
  bucketName: qctest
  endpoint: http://oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAIqM1yei0xXdQ7
  accessKeySecret: 0T01csJF2SvRsFybw9X1g8s6dGxDO9